### ISSUE TITLE
Quick instantiation of Enums

### ISSUE THREAD

**Issue by Namoshek** [consistence/consistence#29] opened 2018-09-05 08:32 UTC
I'm wondering why it needs to be so complicated to instantiate an enum with `MyEnum::get(MyEnum::SOME_VALUE_CONSTANT)`. Personally, I find this quite verbose. A less verbose variant could be to use magic functions like `MyEnum::SOME_VALUE_CONSTANT()` instead. Of course this is somewhat less safe, but with PhpDoc it would still be possible to enumerate available functions which adds IDE support.

I think an implementation could look something like this:
```
public static function __callStatic($name, $arguments)
{
    $values = static::getAvailableValues();
    if (array_key_exists($name, $values)) {
        return new static($values[$name]);
    }

   throw new InvalidEnumValueException($name, $values);
}
```

On the enum itself we could then define static methods via PhpDoc comments:
```
/**
 * @method static NONE()
 * @method static SOME()
 * @method static ALL()
 */
class MyEnum extends \Consistence\Enum\Enum
{
    const NONE = 'none';
    const SOME = 'some';
    const ALL = 'all';
}
```

I appreciate your thoughs on this topic!

**Comment by VasekPurchart** [comment] 2018-09-05 08:38
Duplicate of #17, please see the reasoning there.

Also by writing these PHPDocs you would need something to ensure that they are consistent with the actual available values.

**Closed by VasekPurchart** 2018-09-05 08:38 UTC
